### ISSUE TITLE
Review turnstile migration

### ISSUE THREAD

**Issue by garethtdavies** [garethtdavies/zqw-docs#1]
@adityapk00

I have finished the turnstile migration page. Can you review this for accuracy as I wasn't exactly sure what would happen if you close the wallet and don't open it until a few planned txs would have occurred?

https://garethtdavies.github.io/zqw-docs/turnstile-migration/

(note the rest of docs have not been proofed yet)

**Comment by adityapk00** [comment]
This is great, and accurate.

1. In "You must create a backup once the turnstile migration has started...", the t-Addresses are actually created right after you hit "OK", and before you get the confirmation, where it asks you to backup the wallet. Maybe you can say "You must create a backup after confirming the migration...", so people don't wait for the first tx to finish.
2. If the wallet is not opened for a while, it will behave exactly as you have described it. Any pending Txns are executed serially, so if you've not opened it in a while, it might execute two or more steps back-to-back, so you might be giving up some privacy.
3. In "Aborting the turnstile migration", you can also maybe add that "After aborting, all the funds remain in the addresses when you aborted them, so some of your funds may also be in transparent addresses. Note that aborting the migration doesn't undo or rollback any transactions"

This page looks fantastic, by the way!

Thanks,
Aditya

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by garethtdavies** [comment]
Perfect, thanks added.
