### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by garethtdavies** [garethtdavies/zqw-docs#3]
@adityapk00 I've now proofed the Installation instructions which includes the compiling and build environment. The latter I've largely copied from the existing wiki and cleaned a bit.

I've updated all references from your repo to the ZcashFoundation one but when you are compiling zcashd you are using a version in your repo. Is this a specific version or can I simply update this to point to the zcash/zcash one e.g.

https://github.com/garethtdavies/zqw-docs/blob/dev/docs/setting-up-build-env.md#compiling-zcashd-for-embedded-zcashd

Docs are here: https://garethtdavies.github.io/zqw-docs/installation/

**Comment by adityapk00** [comment]
The zcashd compilation is specific to adityapk00/zcashd, since I have some custom patches for new RPC calls that help with the embedding of zcashd. I think you can just leave it pointed to adityapk00/zcashd.

**Comment by garethtdavies** [comment]
Yes I’ll do that - just wanted to double check that. I’ll actually make a note about that too. Thanks.
